package oauth

import (
	"context"
	"crypto/rsa"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math/big"
	"net/http"
	"sync"
	"time"

	"github.com/Kynettic-org/kynettic-backend/internal/config"
	"github.com/Kynettic-org/kynettic-backend/pkg/logger"
	"github.com/golang-jwt/jwt/v5"
	"go.uber.org/zap"
)

// AppleIDTokenClaims represents the fields we care about from Apple's ID token.
type AppleIDTokenClaims struct {
	Email         string `json:"email"`
	EmailVerified string `json:"email_verified"`
	Audience      string `json:"aud"`
	Issuer        string `json:"iss"`
	Subject       string `json:"sub"`
	Nonce         string `json:"nonce"`
	jwt.RegisteredClaims
}

type appleJWK struct {
	Kty string `json:"kty"`
	Kid string `json:"kid"`
	Use string `json:"use"`
	Alg string `json:"alg"`
	N   string `json:"n"`
	E   string `json:"e"`
}

type appleJWKS struct {
	Keys []appleJWK `json:"keys"`
}

var (
	appleJWKSCache struct {
		sync.RWMutex
		keys   appleJWKS
		expiry time.Time
	}

	appleJWKSURL = "https://appleid.apple.com/auth/keys"
)

// VerifyAppleIDToken verifies a Sign in with Apple ID token by validating its
// signature against Apple's JWKS and checking standard claims, including the nonce.
// nonce must be the raw (unhashed) value generated by the client before the OAuth flow.
// Apple embeds SHA-256(nonce) in the token; this function performs that comparison.
func VerifyAppleIDToken(ctx context.Context, cfg *config.AppleAuthConfig, idToken, nonce string) (*AppleIDTokenClaims, error) {
	if cfg == nil || cfg.ClientID == "" {
		return nil, errors.New("apple login is not configured")
	}

	parser := jwt.NewParser(jwt.WithValidMethods([]string{"RS256"}))
	claims := &AppleIDTokenClaims{}

	keyfunc := func(token *jwt.Token) (interface{}, error) {
		kid, _ := token.Header["kid"].(string)
		if kid == "" {
			return nil, errors.New("apple token missing kid")
		}

		jwk, err := getAppleKey(ctx, kid)
		if err != nil {
			return nil, err
		}

		return jwkToPublicKey(jwk)
	}

	parsedToken, err := parser.ParseWithClaims(idToken, claims, keyfunc)
	if err != nil {
		logger.Warn("Apple ID token parse failed", zap.Error(err))
		return nil, fmt.Errorf("parse apple id token: %w", err)
	}
	if !parsedToken.Valid {
		logger.Warn("Apple ID token invalid after parsing")
		return nil, errors.New("invalid apple id token")
	}

	// Validate issuer and audience.
	if claims.Issuer != "https://appleid.apple.com" {
		logger.Warn("Apple token issuer mismatch", zap.String("issuer", claims.Issuer))
		return nil, errors.New("invalid apple token issuer")
	}
	if claims.Audience != cfg.ClientID {
		logger.Warn("Apple token audience mismatch", zap.String("audience", claims.Audience))
		return nil, errors.New("apple token audience does not match configured client ID")
	}

	if claims.Email == "" {
		return nil, errors.New("apple token missing email")
	}
	if claims.EmailVerified != "true" {
		return nil, errors.New("apple email is not verified")
	}

	// Verify nonce: Apple embeds hex(SHA-256(nonce)) in the token.
	hash := sha256.Sum256([]byte(nonce))
	expectedNonce := hex.EncodeToString(hash[:])
	if claims.Nonce != expectedNonce {
		logger.Warn("Apple token nonce mismatch")
		return nil, errors.New("apple token nonce mismatch")
	}

	return claims, nil
}

func getAppleKey(ctx context.Context, kid string) (*appleJWK, error) {
	jwks, err := loadAppleJWKS(ctx)
	if err != nil {
		return nil, err
	}
	for _, k := range jwks.Keys {
		if k.Kid == kid {
			return &k, nil
		}
	}
	return nil, errors.New("apple signing key not found for kid")
}

func loadAppleJWKS(ctx context.Context) (*appleJWKS, error) {
	appleJWKSCache.RLock()
	if time.Now().Before(appleJWKSCache.expiry) && len(appleJWKSCache.keys.Keys) > 0 {
		defer appleJWKSCache.RUnlock()
		return &appleJWKSCache.keys, nil
	}
	appleJWKSCache.RUnlock()

	appleJWKSCache.Lock()
	defer appleJWKSCache.Unlock()

	// Double-check after acquiring write lock.
	if time.Now().Before(appleJWKSCache.expiry) && len(appleJWKSCache.keys.Keys) > 0 {
		return &appleJWKSCache.keys, nil
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, appleJWKSURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create apple jwks request: %w", err)
	}

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		logger.Error("Apple JWKS fetch failed", zap.Error(err))
		return nil, fmt.Errorf("fetch apple jwks: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		logger.Error("Apple JWKS returned non-OK status", zap.Int("status", resp.StatusCode))
		return nil, fmt.Errorf("apple jwks returned status %d", resp.StatusCode)
	}

	var keys appleJWKS
	if err := json.NewDecoder(resp.Body).Decode(&keys); err != nil {
		return nil, fmt.Errorf("decode apple jwks: %w", err)
	}

	appleJWKSCache.keys = keys
	appleJWKSCache.expiry = time.Now().Add(5 * time.Minute)

	return &appleJWKSCache.keys, nil
}

func jwkToPublicKey(jwk *appleJWK) (*rsa.PublicKey, error) {
	if jwk.Kty != "RSA" {
		return nil, errors.New("unsupported apple jwk kty")
	}
	if jwk.N == "" || jwk.E == "" {
		return nil, errors.New("apple jwk missing modulus or exponent")
	}

	nBytes, err := base64.RawURLEncoding.DecodeString(jwk.N)
	if err != nil {
		return nil, fmt.Errorf("decode apple jwk n: %w", err)
	}
	eBytes, err := base64.RawURLEncoding.DecodeString(jwk.E)
	if err != nil {
		return nil, fmt.Errorf("decode apple jwk e: %w", err)
	}

	n := new(big.Int).SetBytes(nBytes)
	var eInt int
	for _, b := range eBytes {
		eInt = eInt<<8 + int(b)
	}
	if eInt == 0 {
		return nil, errors.New("invalid apple jwk exponent")
	}

	return &rsa.PublicKey{N: n, E: eInt}, nil
}
