package oauth

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"time"

	"github.com/Kynettic-org/kynettic-backend/internal/config"
	"github.com/Kynettic-org/kynettic-backend/pkg/logger"
	"go.uber.org/zap"
)

// GoogleIDTokenPayload represents the subset of fields we care about from Google's
// tokeninfo endpoint response.
type GoogleIDTokenPayload struct {
	Issuer        string `json:"iss"`
	Audience      string `json:"aud"`
	Email         string `json:"email"`
	EmailVerified string `json:"email_verified"`
	Subject       string `json:"sub"`
	Nonce         string `json:"nonce"`
}

// VerifyGoogleIDToken verifies a Google ID token using the tokeninfo endpoint.
// It checks the issuer, audience, email verification, and nonce. It does not
// require storing or managing Google public keys locally.
// nonce must be the raw value generated by the client before the OAuth flow.
func VerifyGoogleIDToken(ctx context.Context, cfg *config.GoogleAuthConfig, idToken, nonce string) (*GoogleIDTokenPayload, error) {
	if cfg == nil || len(cfg.ClientIDs) == 0 {
		return nil, errors.New("google login is not configured")
	}

	endpoint := "https://oauth2.googleapis.com/tokeninfo?id_token=" + url.QueryEscape(idToken)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("create google tokeninfo request: %w", err)
	}

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		logger.Error("Google tokeninfo request failed", zap.Error(err))
		return nil, fmt.Errorf("call google tokeninfo: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		logger.Warn("Google tokeninfo returned non-OK status", zap.Int("status", resp.StatusCode))
		return nil, fmt.Errorf("google tokeninfo returned status %d", resp.StatusCode)
	}

	var payload GoogleIDTokenPayload
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		logger.Error("Google tokeninfo decode failed", zap.Error(err))
		return nil, fmt.Errorf("decode google tokeninfo response: %w", err)
	}

	// Validate issuer.
	if payload.Issuer != "accounts.google.com" && payload.Issuer != "https://accounts.google.com" {
		logger.Warn("Google token issuer mismatch", zap.String("issuer", payload.Issuer))
		return nil, errors.New("invalid google token issuer")
	}

	// Validate audience against configured client IDs.
	validAud := false
	for _, aud := range cfg.ClientIDs {
		if payload.Audience == aud {
			validAud = true
			break
		}
	}
	if !validAud {
		logger.Warn("Google token audience mismatch", zap.String("audience", payload.Audience))
		return nil, errors.New("google token audience does not match configured client IDs")
	}

	if payload.Email == "" {
		return nil, errors.New("google token missing email")
	}

	if payload.EmailVerified != "true" {
		return nil, errors.New("google email is not verified")
	}

	// Verify nonce: Google returns the raw nonce in the tokeninfo response.
	if payload.Nonce != nonce {
		logger.Warn("Google token nonce mismatch")
		return nil, errors.New("google token nonce mismatch")
	}

	return &payload, nil
}
